### PR TITLE
Add an option to generate label points in place of polygons

### PR DESCRIPTION
**Pull request by e-n-f**
## 2.9.0

* Add an option to generate label points in place of polygons
* Add --order-smallest-first and --order-largest-first options
* When tiny polygons are being aggregated into dust, keep the attributes of the largest.

### CODE REVIEW

**Comment by bdon** [comment]
Would using a more sophisticated labeling algorithm like [polylabel](https://github.com/mapbox/polylabel) be in scope for this feature in the future?

**Comment by e-n-f** [comment]
@bdon Yes, that is what I am meaning to do. The centroid code here is just a placeholder until I can get something better working.

**Comment by e-n-f** [comment]
Polylabel turned out to be quite slow, so I used Turf's center-of-mass algorithm instead.

**Comment by jingsam** [comment]
I think this feature is out of scope tippecanoe should implement. There are several algorithms that can extract label point from polygon, but not one algorithm cover every use case. Users should use preferred GIS tools to process data before feeding into tippecanoe, not doing this in tippecanoe. 
Now tippecanoe  has too many feature flags and doing too much things. Remember the "KISS" principle. I suggest tippecanoe should **do one thing and doing well**, the **one thing** is vector tiling.

**Comment by e-n-f** [comment]
@jingsam Thanks for the suggestion. This straddles the line, as something that could mostly be done with preprocessing, but produces better results if it can be sensitive to zoom levels and tile boundaries. Doing a good job of fulfilling the needs of Felt's data ingestion pipeline is more important to me than maintaining the abstract purity of the tool is.

**Pull request merged**
