### PR TITLE
Improve precision of get_area by using long double

### PR DESCRIPTION
**Pull request by romankaravia**
Fixes https://github.com/mapbox/tippecanoe/issues/866

### CODE REVIEW

**Comment by e-n-f** [comment]
Thanks! I'll try to find a minimal test case to demonstrate the bug and fix and then merge this.

**Comment by e-n-f** [comment]
Thanks! Still looking for a good test case to include in the test suite, but this fixes a problem I have been running into where holes are not properly being cut out of certain complex polygons.

**Comment by e-n-f** [comment]
I pulled your change into https://github.com/felt/tippecanoe/pull/19 so I could make additional changes necessary to get consistent behavior between x86 and ARM. Thank you for pointing out and clarifying the problem! I used a sample from your data set as the test.

**Comment by romankaravia** [comment]
Awesome, thank you!

**Pull request closed without merging**
